POST http://localhost:5001/register
Content-Type: application/json

{
    "Nickname": "Pedro2123245",
    "contraseña": "1234",
    "puntos": 0,
    "monedas" : 0,
    "avatar" : "default",
    "piezas" : "default",
    "tablero" : "default"

}